name: Sentry Release

on:
  push:
    branches: [ master ]
  release:
    types: [ published, prereleased ]

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: akashic
          SENTRY_PROJECT: minecraftafkbot
        with:
          environment: production