name: Sentry Release

on:
  push:
    branches: [ master ]
  release:
    types: [ published, prereleased ]

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Create Sentry release
        uses: getsentry/action-release@a74facf8a080ecbdf1cb355f16743530d712abb7 # v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: akashic
          SENTRY_PROJECT: minecraftafkbot
        with:
          environment: production